config/routes.rb
Rails.application.routes.draw do
  resources :movies
  resources :writters
  resources :directors
  resources :actors

end

app/models/actor.rb
class Actor < ActiveRecord::Base
	has_many :movies, as: :person
end

app/models/director.rb
class Director < ActiveRecord::Base
	has_one :movie, as: :person
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  belongs_to :person, polymorphic: true
end

app/models/writter.rb
class Writter < ActiveRecord::Base
	has_one :movie, as: :person
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  before_action :set_actor, only: [:show, :edit, :update, :destroy]

  # GET /actors
  # GET /actors.json
  def index
    @actors = Actor.all
  end

  # GET /actors/1
  # GET /actors/1.json
  def show
  end

  # GET /actors/new
  def new
    @actor = Actor.new
  end

  # GET /actors/1/edit
  def edit
  end

  # POST /actors
  # POST /actors.json
  def create
    @actor = Actor.new(actor_params)

    respond_to do |format|
      if @actor.save
        format.html { redirect_to @actor, notice: 'Actor was successfully created.' }
        format.json { render :show, status: :created, location: @actor }
      else
        format.html { render :new }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /actors/1
  # PATCH/PUT /actors/1.json
  def update
    respond_to do |format|
      if @actor.update(actor_params)
        format.html { redirect_to @actor, notice: 'Actor was successfully updated.' }
        format.json { render :show, status: :ok, location: @actor }
      else
        format.html { render :edit }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /actors/1
  # DELETE /actors/1.json
  def destroy
    @actor.destroy
    respond_to do |format|
      format.html { redirect_to actors_url, notice: 'Actor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_actor
      @actor = Actor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def actor_params
      params.require(:actor).permit(:name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
  before_action :set_director, only: [:show, :edit, :update, :destroy]

  # GET /directors
  # GET /directors.json
  def index
    @directors = Director.all
  end

  # GET /directors/1
  # GET /directors/1.json
  def show
  end

  # GET /directors/new
  def new
    @director = Director.new
  end

  # GET /directors/1/edit
  def edit
  end

  # POST /directors
  # POST /directors.json
  def create
    @director = Director.new(director_params)

    respond_to do |format|
      if @director.save
        format.html { redirect_to @director, notice: 'Director was successfully created.' }
        format.json { render :show, status: :created, location: @director }
      else
        format.html { render :new }
        format.json { render json: @director.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /directors/1
  # PATCH/PUT /directors/1.json
  def update
    respond_to do |format|
      if @director.update(director_params)
        format.html { redirect_to @director, notice: 'Director was successfully updated.' }
        format.json { render :show, status: :ok, location: @director }
      else
        format.html { render :edit }
        format.json { render json: @director.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /directors/1
  # DELETE /directors/1.json
  def destroy
    @director.destroy
    respond_to do |format|
      format.html { redirect_to directors_url, notice: 'Director was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_director
      @director = Director.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def director_params
      params.require(:director).permit(:name)
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:name, :person_id, :person_type)
    end
end

app/controllers/writters_controller.rb
class WrittersController < ApplicationController
  before_action :set_writter, only: [:show, :edit, :update, :destroy]

  # GET /writters
  # GET /writters.json
  def index
    @writters = Writter.all
  end

  # GET /writters/1
  # GET /writters/1.json
  def show
  end

  # GET /writters/new
  def new
    @writter = Writter.new
  end

  # GET /writters/1/edit
  def edit
  end

  # POST /writters
  # POST /writters.json
  def create
    @writter = Writter.new(writter_params)

    respond_to do |format|
      if @writter.save
        format.html { redirect_to @writter, notice: 'Writter was successfully created.' }
        format.json { render :show, status: :created, location: @writter }
      else
        format.html { render :new }
        format.json { render json: @writter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /writters/1
  # PATCH/PUT /writters/1.json
  def update
    respond_to do |format|
      if @writter.update(writter_params)
        format.html { redirect_to @writter, notice: 'Writter was successfully updated.' }
        format.json { render :show, status: :ok, location: @writter }
      else
        format.html { render :edit }
        format.json { render json: @writter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /writters/1
  # DELETE /writters/1.json
  def destroy
    @writter.destroy
    respond_to do |format|
      format.html { redirect_to writters_url, notice: 'Writter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_writter
      @writter = Writter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def writter_params
      params.require(:writter).permit(:name)
    end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/directors_helper.rb
module DirectorsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/writters_helper.rb
module WrittersHelper
end

app/views/actors/_form.html.erb
<%= form_for(@actor) do |f| %>
  <% if @actor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@actor.errors.count, "error") %> prohibited this actor from being saved:</h2>

      <ul>
      <% @actor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/actors/edit.html.erb
<h1>Editing Actor</h1>

<%= render 'form' %>

<%= link_to 'Show', @actor %> |
<%= link_to 'Back', actors_path %>

app/views/actors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Actors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @actors.each do |actor| %>
      <tr>
        <td><%= actor.name %></td>
        <td><%= link_to 'Show', actor %></td>
        <td><%= link_to 'Edit', edit_actor_path(actor) %></td>
        <td><%= link_to 'Destroy', actor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Actor', new_actor_path %>

app/views/actors/new.html.erb
<h1>New Actor</h1>

<%= render 'form' %>

<%= link_to 'Back', actors_path %>

app/views/actors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @actor.name %>
</p>

<%= link_to 'Edit', edit_actor_path(@actor) %> |
<%= link_to 'Back', actors_path %>

app/views/directors/_form.html.erb
<%= form_for(@director) do |f| %>
  <% if @director.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@director.errors.count, "error") %> prohibited this director from being saved:</h2>

      <ul>
      <% @director.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/directors/edit.html.erb
<h1>Editing Director</h1>

<%= render 'form' %>

<%= link_to 'Show', @director %> |
<%= link_to 'Back', directors_path %>

app/views/directors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Directors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @directors.each do |director| %>
      <tr>
        <td><%= director.name %></td>
        <td><%= link_to 'Show', director %></td>
        <td><%= link_to 'Edit', edit_director_path(director) %></td>
        <td><%= link_to 'Destroy', director, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Director', new_director_path %>

app/views/directors/new.html.erb
<h1>New Director</h1>

<%= render 'form' %>

<%= link_to 'Back', directors_path %>

app/views/directors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @director.name %>
</p>

<%= link_to 'Edit', edit_director_path(@director) %> |
<%= link_to 'Back', directors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :person_id %><br>
    <%= f.text_field :person_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Movies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Person</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.name %></td>
        <td><%= movie.person %></td>
        <td><%= link_to 'Show', movie %></td>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie', new_movie_path %>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @movie.name %>
</p>

<p>
  <strong>Person:</strong>
  <%= @movie.person %>
</p>

<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>

app/views/writters/_form.html.erb
<%= form_for(@writter) do |f| %>
  <% if @writter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@writter.errors.count, "error") %> prohibited this writter from being saved:</h2>

      <ul>
      <% @writter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/writters/edit.html.erb
<h1>Editing Writter</h1>

<%= render 'form' %>

<%= link_to 'Show', @writter %> |
<%= link_to 'Back', writters_path %>

app/views/writters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Writters</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @writters.each do |writter| %>
      <tr>
        <td><%= writter.name %></td>
        <td><%= link_to 'Show', writter %></td>
        <td><%= link_to 'Edit', edit_writter_path(writter) %></td>
        <td><%= link_to 'Destroy', writter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Writter', new_writter_path %>

app/views/writters/new.html.erb
<h1>New Writter</h1>

<%= render 'form' %>

<%= link_to 'Back', writters_path %>

app/views/writters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @writter.name %>
</p>

<%= link_to 'Edit', edit_writter_path(@writter) %> |
<%= link_to 'Back', writters_path %>